# Generated by Django 3.2.5 on 2023-02-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_id',
            field=models.IntegerField(null=True),
        ),
    ]
